### ISSUE TITLE
Modal appears on parent page but not `fullScreenModal` child [iOS only]

### ISSUE THREAD

**Issue by david-gettins** [gorhom/react-native-bottom-sheet#324]
# Bug

When using the bottom sheet modal it opens on my root page but not a child page using full screen modal stack presentation. To clarify the modal opens but is not visible on the child page only when you navigate back to the root page. This only happens on iOS, the bottom sheet modal works as expected on Android.

**Child Page Navigation Options**
```typescript
const childPageOptions: NativeStackNavigationOptions = {
  stackPresentation: 'fullScreenModal',
}
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.1  |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.3   |
| react-native-gesture-handler    | 1.10.1   |

## Steps To Reproduce

1. Wrap `App` component with `BottomSheetModalProvider`
2. Add a `BottomSheetModal` as a child of the `App` component
3. Add a child route with the `stackPresentation` option set to `fullScreenModal`
4. Run the app
5. Navigate to child page
6. Open the bottom sheet modal
7. Bottom sheet does not appear
8. Go back to parent route
9. See bottom sheet modal open.

Describe what you expected to happen:

1. Bottom sheet modals should appear over `fullScreenModal` pages.

## Reproducible sample code

_Cannot at this time._

**Comment by zhigang1992** [comment]
If you're using react-native-screens native stack, then each ViewController is its own separate react native view.

Wrapping the app with provider will only show the content on root page.

To have it show up in child screen, wrap your child component with `BottomSheetModalProvider`

Which is still not perfect since the view size is no longer full screen. And only the visible area of the child VC.

It's the same thing if you use things like react-native-safe-area-inset or react-native-portal. You have to wrap each of your screen to get them working correctly.

**Comment by david-gettins** [comment]
Thank you, that worked. 

I should have looked at the example app as that illustrates it there.
