### ISSUE TITLE
Elevation issue

### ISSUE THREAD

**Issue by mrsilph** [gorhom/react-native-bottom-sheet#387]
## Ask your Question

Hi! How can I set the elevation of the bottom sheet?

As you can see in the photo, some components that are under the sheet but have and elevation value of 5 (for shadows in android) are been drawn on the sheet, that isn't desirable. Thanks!

![Capture](https://user-images.githubusercontent.com/47247073/113522282-7cbc8380-959f-11eb-9fa8-5316a0a45d08.PNG)

**Comment by gorhom** [comment]
hi @darmane, i will add a new guide to the documentations soon 👍

**Comment by gorhom** [comment]
guide been added https://gorhom.github.io/react-native-bottom-sheet/adding-shadow

**Comment by mrsilph** [comment]
Thank you! I'll check it tomorrow

**Comment by safeer-ahmed** [comment]
@gorhom still its not working in Android

**Comment by virus2016** [comment]
Don't understand how to add a shadow using the guide, no code example...

**Comment by gorhom** [comment]
@virus2016 https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/advanced/ShadowExample.tsx

**Comment by mmmoussa** [comment]
Hi @gorhom, I believe you have misunderstood the issue that is being reported here, and is also reported in other issues such as #398 and #692. The problem is not adding a shadow to the bottom sheet as you've provided an example for, but rather, having the bottom sheet appear above elements that should be below it but make use of the `elevation` prop on Android. Android lays elements with higher elevation on top of elements with lower elevation, and since the bottom sheet has low elevation by default (that is not configurable), it breaks whenever you need to render components on the screen behind it that need an elevation greater than 0. This is what's being shown in @darmane's screenshot. The +/- counter component and the weekday circles are not part of the bottom sheet. They are supposed to be rendered on the screen *behind* the bottom sheet. This is easily reproducible by drawing a component on the screen with a non-zero elevation and then opening the bottom sheet to cover it on Android.

**Comment by erickreutz** [comment]
@gorhom I follow your guide for adding a shadow to `BottomSheetModal1 and my logs are littered with `WARN  (ADVICE) View #1093 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a solid background color to fix this, or apply the shadow to a more specific component.` is this expected?
