### ISSUE TITLE
Closing Bottom Sheet when Keyboard is Shown

### ISSUE THREAD

**Issue by carissacks** [gorhom/react-native-bottom-sheet#478]
# Bug

Hello, I got this weird behavior whenever I tried to close the bottom sheet on Android while my keyboard is shown. I did try using the latest version (v 4.0.8 alpha), and it's still there. However it works fine in ios.

This project is on Expo (v 41.0.0)

![android](https://user-images.githubusercontent.com/46070698/120756716-cc84e000-c539-11eb-83cb-bc591021aa1d.gif)

- Closing the bottom sheet doesn't seems to close it completely, you can see it still being displayed behind the keyboard. This existing bottom sheet however doesn't seem to close even thought I called close method by pressing `Close` button.
- I close the keyboard manually on `onChange` callback, when the index is smaller or equal to 0. However when clicking on the backdrop, the keyboard isn't dismissed.
- Also tried to expand the bottom sheet to fullScreen when keyboard is displayed, but the bottom sheet size keeps changing.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.5  |
| react-native                    | 0.3.6  |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

1. Run the snack in Android
2. Press 'Open'
3. Focus on the text input 'email', located under the close text on the bottom sheet
- Here you can see the bottom sheet doesn't expand to fullscreen.
4. Press 'Close', located inside the bottom sheet
- You can see the bottom sheet still exists shortly after the keyboard is dismissed.
5. Repeat step 2 and 3
6. Press the backdrop (anywhere outside the bottom sheet)
- The keyboard is not dismissed
7. Press back to close the keyboard
8. Try pressing the backdrop or 'Close' to close the bottom sheet

Describe what you expected to happen:

![ios](https://user-images.githubusercontent.com/46070698/120758378-f6d79d00-c53b-11eb-9f92-454692ceb0ef.gif)

1. Focusing on the text input will expand the bottom sheet to fullscreen.
2. Calling `bottomsheet.close()` or pressing on the backdrop will close the bottom sheet completely.

## Reproducible sample code

See it here https://snack.expo.io/@carissa_cks/bottom-sheet

Related issue: #453 

And thank you for this awesome package!!

**Comment by usamaasfar** [comment]
same issue

**Comment by gorhom** [comment]
hi @carissacks , @usama-asfar  could you test on `v4`  #427 ?

```bash
yarn add @gorhom/bottom-sheet@4.0.0-alpha.9
```

**Comment by usama-asfar** [comment]
Thanks, @gorhom for the response

Fix the issue by changing `android:windowSoftInputMode="adjustResize"` to `android:windowSoftInputMode="adjustPan"` on `AndroidManifest.xml`

**Comment by usamaasfar** [comment]
> hi @carissacks , @usama-asfar could you test on `v4` #427 ?
> 
> ```shell
> yarn add @gorhom/bottom-sheet@4.0.0-alpha.9
> ```

Thanks, @gorhom, This version fixes the issue.

**Comment by gorhom** [comment]
this should be resolve with https://github.com/gorhom/react-native-bottom-sheet/commit/8f34990436f8cc8c1ec1c545488d77db5845166c on the next release 👍

**Comment by carissacks** [comment]
Thanks for the fast response @gorhom !! I tested my implementation on v4 alpha 9 but it still doesn't work. Do you mind sharing your implementation here @usama-asfar ?

**Comment by usamaasfar** [comment]
@carissacks 

```js
import React, { useMemo } from 'react';
import {
  BottomSheetTextInput,
  BottomSheetModal,
  BottomSheetModalProvider,
  BottomSheetView,
} from '@gorhom/bottom-sheet';

import { useTheme } from '../../../ui/Theme';

import { LocationAutocomplete } from '../../../components';

export default function ExploreBottomSheet({ setRef }) {
  const theme = useTheme();

  const snapPoints = useMemo(
    () => [theme.box.height * 7, theme.screen.height], //  theme.screen.height = Dimensions.get('window').height
    [],
  );

  return (
    <BottomSheetModalProvider>
      <BottomSheetModal
        ref={setRef}
        handleComponent={null}
        enableDismissOnClose={false}
        enablePanDownToClose={false}
        keyboardBehavior="extend"
        snapPoints={snapPoints}>
        <BottomSheetView>
          <LocationAutocomplete
            propsInput={{
              TextInputRenderComponent: BottomSheetTextInput,
            }}
          />
        </BottomSheetView>
      </BottomSheetModal>
    </BottomSheetModalProvider>
  );
}

```

I have replace `TextInput` with `BottomSheetTextInput`

**Comment by carissacks** [comment]
Thank you for sharing your code. Turns out I need to add 
```json
    "android": {
      "softwareKeyboardLayoutMode":"pan"
    }
```
in `app.json`, and now it all works well

**Comment by gorhom** [comment]
@carissacks @usama-asfar i have added `android_keyboardInputMode` to `BottomSheet` to solve this issue! have a look at the commit https://github.com/gorhom/react-native-bottom-sheet/commit/069c4b6742630dc5fa7d4763a5c4dc6bfec439cc

**Comment by carissacks** [comment]
> @carissacks @usama-asfar i have added `android_keyboardInputMode` to `BottomSheet` to solve this issue! have a look at the commit [069c4b6](https://github.com/gorhom/react-native-bottom-sheet/commit/069c4b6742630dc5fa7d4763a5c4dc6bfec439cc)

Thank you for telling us more about the detail and being extra responsive 🎉 . However the issue still seems to exist when I'm using the default value of `softwareKeyboardLayoutMode`. I still have the bottom sheet height changing when trying to set it to full-screen. And I still have the bottom sheet not completely dismissed when I tried to close it while the keyboard is displayed 😢

**Comment by pfcodes** [comment]
Having this problem on iOS when `keyboardBehavior` is `restore`, anybody know how to fix this problem with this situation?

**Comment by beqramo** [comment]
yes on ios it still exists, in the end, I use only one snap point and the next step points are controlled by the snapToPosition function. somehow it has problems with many declared snapPoints

**Comment by bryanprimus** [comment]
this issue still exist,

when navigating to a new screen while the keyboard is previously open, it only dismisses the keyboard.

**Comment by alexey-kachalov** [comment]
It still exists on Android, but not on all devices. It hides a dialog when focus to an input when keyboard appears.

**Comment by avdieiev-v** [comment]
> It still exists on Android, but not on all devices. It hides a dialog when focus to an input when keyboard appears.

i have fixed this by adding enableDismissOnClose={false}

**Comment by alexey-kachalov** [comment]
> i have fixed this by adding enableDismissOnClose={false}

I have actually done the same. :) However, further investigations showed that adding `enableDismissOnClose={false}` is not sufficient.

I am using `@gorhom/bottom-sheet` version `4.6.1`.

Here's what happens when the input field is clicked: the keyboard pops up → the height of the bottom sheet changes → the position of the animation interpolates to `-1` → consequently, `onClose` is triggered in `BottomSheet::useAnimatedReaction`, which in turn calls `BottomSheetModal::handleBottomSheetOnClose` → herein, the code `if (enableDismissOnClose) unmount();` is executed due to `enableDismissOnClose` being set by default → the bottom sheet is then unmounted. Therefore, setting `enableDismissOnClose={false}` resolves this issue, BUT...

When `enableDismissOnClose={false}` is added, a new issue emerges: it becomes impossible to reopen the dialog. The problem lies in the same place: `if (enableDismissOnClose) unmount();` doesn't call unmount as `enableDismissOnClose` was disabled 😁. The bottom sheet doesn't respond to `present()`, supposing that the dialog is already mounted.

Solution: There's a `forcedDismissed` ref, which is set upon explicit calling of `BottomSheetModal::dismiss()`. The condition was altered to `if (enableDismissOnClose || forcedDismissed.current) unmount();` which allowed the code to function as expected. Post invocation of `dismiss()`, unmounting follows, and subsequently, the dialog can be normally called via `present()`.

We have patch to the NPM for now and the code for `https://github.com/gorhom/react-native-bottom-sheet/blob/v4.6.1/src/components/bottomSheetModal/BottomSheetModal.tsx#L343` looks like this:

```js
if (enableDismissOnClose || forcedDismissed.current) {
  unmount();
}
```

I decided not to create a new issue due to the complete history being present here. Let me just CC @gorhom. Thank you.

**Comment by avdieiev-v** [comment]
@alexey-kachalov Thank you, I've applied the patch and everything works correctly now. Found the same issue as you explained.
