### ISSUE TITLE
[v4] Backdrops not displaying

### ISSUE THREAD

**Issue by julienripet** [gorhom/react-native-bottom-sheet#634]
# Bug

Backdrop components do not display unless you have 2 or more snapPoints

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0   |
| react-native                    | 0.64.0  |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Create a new BottomSheet
2. Import {BottomSheetBackdrop} from @gorhom/bottom-sheet
3. Set only one SnapPoint

Describe what you expected to happen:

1. I expect the backdrop to display if the bottomsheet is open

## Reproducible sample code

As a sidenote, the doc still says 

``` 
snapPoints={[-1, '100%']}
```
even though `-1` is no longer a valid SnapPoint

**Comment by sorioinc** [comment]
It was happening to me as well, but this comment from the author helped me solve the issue: https://github.com/gorhom/react-native-bottom-sheet/issues/585#issuecomment-900619713

I was setting the back drop like:
`backdropComponent={BottomSheetBackdrop}`
instead of
`backdropComponent={renderBackdrop}`

where `renderBackdrop` is:
```js
  const renderBackdrop = useCallback(
    // eslint-disable-next-line react/jsx-props-no-spreading
    props => <BottomSheetBackdrop disappearsOnIndex={-1} appearsOnIndex={0} {...props} />,
    [],
  );
```

**Comment by gorhom** [comment]
thanks @sorioinc for answering this issue, also i have updated the website docs to remove `-1` from snap points prop
