### ISSUE TITLE
focusHook examples

### ISSUE THREAD

**Issue by Gnative** [gorhom/react-native-bottom-sheet#727]
I'm trying to understand how to implement `focusHook`, is there an example other than using `useFocusHook` from react-navigation ?

Thank you so much for this wonderful component

**Comment by fiznool** [comment]
I came across a use case today for `focusHook` and thought I'd document my findings, in case it is helpful.

My screen contains a horizontal snap carousel with 2 slides, and a `BottomSheet` component. The contents of the `BottomSheet` changes depending on the slide which is snapped to. I wanted to use fade animations on the `BottomSheet` content, so both content elements are present, and are shown/hidden by changing `opacity`. As a result, there are multiple `BottomSheet*` content nodes present inside the parent `BottomSheet`, but only one is shown at a time.

I was coming across an issue where scrolling would not work on some of the `BottomSheet` contents, presumably because one of the hidden content components was trapping the focus. After studying the [source code for useFocusEffect](https://github.com/react-navigation/react-navigation/blob/b91c9b05ff96727f5fa6ef0bec51b5d7eac06600/packages/core/src/useFocusEffect.tsx), I solved this using `focusHook` as shown in the following code snippet:

``` jsx
const MyComponent = () => {
  const [slideIndex, setSlideIndex] = useState(0);

  const useSlide1FocusEffect = (effect) => {
    useEffect(() => {
      if (slideIndex === 0) {
        return effect();
      }
    }, [effect]);
  };

  const useSlide2FocusEffect = (effect) => {
    useEffect(() => {
      if (slideIndex === 1) {
        return effect();
      }
    }, [effect]);
  };

  return (
    <View>
      <SnapCarousel onSnap={setSlideIndex}>
        <Slide title="Slide 1" />
        <Slide title="Slide 2" />
      </SnapCarousel>
      <BottomSheet>
        {/* The following is simplified, opacity is actually controlled by an `Animated.Value` from the carousel scroll position */}
        <View style={[StyleSheet.absoluteFill, { opacity: slideIndex === 0 ? 1 : 0 }>
          <BottomSheetView focusHook={useSlide1FocusEffect} />
        </View>
        <View style={[StyleSheet.absoluteFill, { opacity: slideIndex === 1 ? 1 : 0 }>
          <BottomSheetView focusHook={useSlide2FocusEffect} />
        </View>
      </BottomSheet>
  );
}
```

The gist of the hook: it is passed an `effect` callback by the BottomSheet library, and this should be called whenever the component in question needs to request focus. So, in this example, `useSlide1FocusEffect` is attached to the `BottomSheetView`, which is shown (opacity of 1) when the snap carousel is at index 0 - meaning that the hook calls `effect` when `slideIndex` is `0`.

Hope this helps!
